  name: Update Artifact Version
  description: Update artifact version by pushing a bump of patch version back to the repo. Expects semver, e.g., 'version=1.0.2'
  inputs:
    version_file_name:
      description: 'The name of the file containing the version number'
      required: false
    version_variable_name:
      description: 'The name of the variable containing the version number'
      required: false
    push-back-to-repo:
      description: 'Whether to push the new version back to the repo'
      required: false
      default: 'true'
    previous-version:
      description: 'The previous (semver) version of the artifact'
      required: false

  outputs:
    version:
      value: ${{ env.VERSION }}
      description: 'The new version of the artifact'


  runs:
    using: "composite"
    steps:
      - name: Get Version Number From File
        if: ${{ inputs.version_file_name }}
        shell: bash
        run: |
          releaseVersion=$(cat ${{ inputs.version_file_name }} | grep "${{ inputs.version_variable_name }}" | cut -d'=' -f2)
          echo "RELEASE_VERSION=$releaseVersion" >> $GITHUB_ENV
      - name: Set Previous Version as ENV variable if passed as input and not file
        if: ${{ !inputs.version_file_name && inputs.previous-version }}
        shell: bash
        run: echo "RELEASE_VERSION=${{ inputs.previous-version }}" >> $GITHUB_ENV
      - name: Increase Version Number By One and export to VERSION env variable
        shell: bash
        run: |
          major=`echo $RELEASE_VERSION | cut -d. -f1`
          minor=`echo $RELEASE_VERSION | cut -d. -f2`
          patch=`echo $RELEASE_VERSIONs | cut -d. -f3`
          patch=`expr $patch + 1`
          version=`echo $major.$minor.$patch`
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Insert new version into file
        shell: bash
        run: |
          sed -i "s/${{ inputs.version_variable_name }}=.*/${{ inputs.version_variable_name }}=$VERSION/" ${{ inputs.version_file_name }}
      - name: Push Version
        if: ${{ inputs.push-back-to-repo == 'true' }}
        shell: bash
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add ${{ inputs.version_file_name }}
          git commit -m "chore(bump): Bump ${{ inputs.version_variable_name }} to $VERSION [skip ci]"
          git push origin $GITHUB_REF_NAME --force
