  name: Update Artifact Version
  description: Update artifact version by pushing a bump of patch version back to the repo. Expects semver, e.g., 'version=1.0.2'
  inputs:
    version_file_name:
      description: 'The name of the file containing the version number'
      required: false
    version_variable_name:
      description: 'The name of the variable containing the version number'
      required: false
    push-back-to-repo:
      description: 'Whether to push the new version back to the repo'
      required: false
      default: 'true'
    previous-version:
      description: 'The previous (semver) version of the artifact'
      required: false

  runs:
    using: "composite"
    steps:
      - name: Get Version Number From File
        if: ${{ inputs.version_file_name }}
        shell: bash
        env:
          GHA_ARTIFACTORY_VERSION_FILE_NAME: ${{ inputs.version_file_name }}
          GHA_ARTIFACTORY_VERSION_VARIABLE_NAME: ${{ inputs.version_variable_name }}
        run: |
          releaseVersion=$(cat ${GHA_ARTIFACTORY_VERSION_FILE_NAME} | grep "${GHA_ARTIFACTORY_VERSION_VARIABLE_NAME}" | cut -d'=' -f2)
          echo "RELEASE_VERSION=$releaseVersion" >> $GITHUB_ENV
      - name: Set Previous Version as ENV variable if passed as input and not file
        if: ${{ !inputs.version_file_name && inputs.previous-version }}
        shell: bash
        env:
          GHA_ARTIFACTORY_PREVIOUS_VERSION: ${{ inputs.previous-version }}
        run: echo "RELEASE_VERSION=${GHA_ARTIFACTORY_PREVIOUS_VERSION}" >> $GITHUB_ENV
      - name: Increase Version Number By One and export to VERSION env variable
        shell: bash
        run: |
          major=`echo $RELEASE_VERSION | cut -d. -f1`
          minor=`echo $RELEASE_VERSION | cut -d. -f2`
          patch=`echo $RELEASE_VERSIONs | cut -d. -f3`
          patch=`expr $patch + 1`
          version=`echo $major.$minor.$patch`
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Insert new version into file
        shell: bash
        env:
          GHA_ARTIFACTORY_VERSION_FILE_NAME: ${{ inputs.version_file_name }}
          GHA_ARTIFACTORY_VERSION_VARIABLE_NAME: ${{ inputs.version_variable_name }}
          GHA_ARTIFACTORY_VERSION: ${{ env.VERSION }}
        run: |
          sed -i "s/${GHA_ARTIFACTORY_VERSION_VARIABLE_NAME}=.*/${GHA_ARTIFACTORY_VERSION_VARIABLE_NAME}=$GHA_ARTIFACTORY_VERSION/" ${GHA_ARTIFACTORY_VERSION_FILE_NAME}
      - name: Push Version
        if: ${{ inputs.push-back-to-repo == 'true' }}
        shell: bash
        env:
            GHA_ARTIFACTORY_GITHUB_REF_NAME: ${{ github.ref }}
            GHA_ARTIFACTORY_VERSION_FILE_NAME: ${{ inputs.version_file_name }}
            GHA_ARTIFACTORY_VERSION_VARIABLE_NAME: ${{ inputs.version_variable_name }}
            GHA_ARTIFACTORY_VERSION: ${{ env.VERSION }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add ${GHA_ARTIFACTORY_VERSION_FILE_NAME}
          git commit -m "chore(bump): Bump ${GHA_ARTIFACTORY_VERSION_VARIABLE_NAME} to $ GHA_ARTIFACTORY_VERSION [skip ci]"
          git push origin $GHA_ARTIFACTORY_GITHUB_REF_NAME --force
