  name: Entur/Artifactory/CI

  on:
    pull_request:

  jobs:
    test-update-version-ok:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/update-version
              with:
                version_file_name: fixture/version-file.good
                version_variable_name: version
                push-back-to-repo: false

    assert-update-version-ok:
        runs-on: ubuntu-24.04
        needs: test-update-version-ok
        steps:
            - uses: nick-fields/assert-action@v2
              with:
                expected: "1.0.0"
                actual: ${{ needs.test-update-version-ok.outputs.version }}

