  name: Entur/Artifactory/CI

  on:
    pull_request:

  jobs:
    test-update-version-ok:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/update-version
              with:
                version_file_name: fixture/version-file.good
                version_variable_name: version
                push-back-to-repo: false
            - shell: bash
              run: |
                if [[ "$VERSION" neq "1.0.0" ]]; then
                  echo "Version $VERSION not equal 1.0.0"
                  exit 1
                fi

