name: Verify Artifactory Credentials

on:
  workflow_call:

jobs:
  verify-login:
    runs-on: ubuntu-24.04

    steps:
      - name: Test Artifactory Login
        run: |
          TEST=JFROG
          RED='\033[0;31m'
          GREEN='\033[0;32m'
          YELLOW='\033[0;33m'
          NEUTRAL='\033[0m'
          if ! curl -u ${ARTIFACTORY_AUTH_USER}:${ARTIFACTORY_AUTH_TOKEN} \
          --head --fail -X GET "${ARTIFACTORY_URL}"; then
            printf "%bERROR%b: Invalid Artifactory credentials\n" "${RED}" "${NEUTRAL}"
            exit 1
          else
            printf "%bOK%b: Artifactory credentials are valid\n" "${GREEN}" "${NEUTRAL}"
          fi
        env:
          ARTIFACTORY_URL: "https://entur2.jfrog.io/router/api/v1/system/ping"
          ARTIFACTORY_AUTH_USER: ${{ secrets.ARTIFACTORY_AUTH_USER }}
          ARTIFACTORY_AUTH_TOKEN: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
